version: "3.8"
services:
  postgres:
    image: timescale/timescaledb-ha:pg16
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: energyleaf
    ports:
      - 5432:5432
    volumes:
      - postgresdata:/home/postgres/pgdata/data
volumes:
  postgresdata:
