services:
  postgres:
    build: "."
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: energyleaf
    ports:
      - 5432:5432
    volumes:
      - postgresdata:/home/postgres/pgdata/data
  minio:
    image: minio/minio:RELEASE.2025-04-22T22-12-26Z
    ports:
      - "9000:9000"   # S3 API port
      - "9001:9001"   # MinIO console port
    volumes:
      - minio-data:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    restart: unless-stopped
volumes:
  postgresdata:
  minio-data:
