apiVersion: v1
kind: Service
metadata:
  name: energyleaf-db-headless
  namespace: energyleaf
  labels:
    app: energyleaf
    component: postgres
spec:
  clusterIP: None
  selector:
    app: energyleaf
    component: postgres
  ports:
    - port: 5432
      targetPort: 5432
