apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: energyleaf-db-pvc
  namespace: energyleaf
  labels:
    app: energyleaf
    component: postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path
