apiVersion: v1
kind: Service
metadata:
  name: energyleaf-db
  namespace: energyleaf
  labels:
    app: energyleaf
    component: postgres
spec:
  type: ClusterIP
  selector:
    app: energyleaf
    component: postgres
  ports:
    - port: 5432
      targetPort: 5432
